### ISSUE TITLE
SipHash WebAssembly RangeError

### ISSUE THREAD

**Issue by s3ththompson** [yoshuawuyts/buffer-graph#2]
This may be irrelevant if you swap out SipHash per #1, but I'm getting [an error](https://github.com/mafintosh/siphash24/issues/2) from the WebAssembly part of SipHash. When I forced the JavaScript version of SipHash, everything worked well and was very fast.

Depending on whether the issue is fixed upstream in SipHash or not, is there any way you can force the JS version in the meantime?

See error below:
```
/usr/local/lib/node_modules/bankai/node_modules/siphash24/index.js:40
    mem.set(data, 24)
        ^

RangeError: Source is too large
    at Uint8Array.set (native)
    at siphash24 (/usr/local/lib/node_modules/bankai/node_modules/siphash24/index.js:40:9)
    at /usr/local/lib/node_modules/bankai/node_modules/buffer-graph/index.js:84:30
    at /usr/local/lib/node_modules/bankai/lib/graph-script.js:55:7
    at /usr/local/lib/node_modules/bankai/node_modules/browserify/index.js:779:13
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/bankai/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:110:20)
    at ConcatStream.emit (events.js:207:7)
    at finishMaybe (/usr/local/lib/node_modules/bankai/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/usr/local/lib/node_modules/bankai/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
```

**Comment by yoshuawuyts** [comment]
Dang, yeah we really ought to swap it for the other one. Siphash was meant for small inputs, that might just be exactly what you're running into (tho I didn't know this when I started using it).

Just out of curiosity: do you have any video in the project at the moment? Video is, like, the one edge case we haven't considered here - too big to hold in memory or optimize for folks (at least now).

**Comment by s3ththompson** [comment]
Hmm, no video (or at least the video is uploaded to a cdn separately). I believe the data buffer for this error was `bundle.js`.

Not sure about whether it's a size issue... the JS version of siphash24 seems to work fine. It's only the WebAssembly issue which errors--maybe a bug in how WebAssembly memory is handled?

**Comment by yoshuawuyts** [comment]
Related https://github.com/mafintosh/siphash24/issues/2

**Comment by yoshuawuyts** [comment]
Saw your repro, think you're on the money here. Dang, we might need to
accelerate our migration to Blake2b it seems - fingers crossed it doesn't
have the same WASM issue.

**Comment by jbergstroem** [comment]
Stability and consistency would definitely play a higher importance than raw hashing speed here.

**Comment by jbergstroem** [comment]
@s3ththompson as part of the new-new-new branch testing I replaced sip with blakejs; perhaps [test it out](https://github.com/jbergstroem/buffer-graph/tree/feature/siphash2blakejs) and see if it solves your problems?

**Comment by s3ththompson** [comment]
@jbergstroem yep, it's working for me now (and still super fast)! I would support a change to blakejs
